# -*- coding: utf-8 -*-
"""segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MBg0EpXztEcL3SLdqUPsi825_z55vC21
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('ggplot')

import nltk
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('maxent_ne_chunker_tab')
nltk.download('words')
nltk.download('vader_lexicon')

import kagglehub

# Download latest version
path = kagglehub.dataset_download("snap/amazon-fine-food-reviews")

print("Path to dataset files:", path)

df = pd.read_csv(f'{path}/Reviews.csv')

df

df['Text'][23]

df['Score'].value_counts().sort_index().plot(kind='bar', title="Count of reviews by star", figsize=(10,8))

example = df['Text'][50]

tokens = nltk.word_tokenize(example)
tokens

# POS Tagin

tagged = nltk.pos_tag(tokens)
tagged

entities = nltk.chunk.ne_chunk(tagged)
entities.pprint()

# VADER
from nltk.sentiment import SentimentIntensityAnalyzer
from tqdm.notebook import tqdm

sia = SentimentIntensityAnalyzer()

sia.polarity_scores("hello guys kay kartay")



res = {}
for example in df['Text']:
  text = df["Text"]
  myid = df['Id']
  res[myid] = sia.polarity_scores(text)

vaders = pd.DataFrame(res).T
vaders

res = {}

for i , row in tqdm(df.iterrows(),total=len(df)):
  text = row["Text"]
  myid = row['Id']
  res[myid] = sia.polarity_scores(text)

vaders = pd.DataFrame(res).T
vaders

vaders = vaders.reset_index().rename(columns={"index":'Id'})

vaders = vaders.merge(df,how = 'left')
vaders

sns.barplot(data=vaders, x = "Score", y = "compound")

fig , axs = plt.subplots(1,3,figsize = (12,3))

sns.barplot(data=vaders, x = "Score", y = "pos" , ax = axs[0])
sns.barplot(data=vaders, x = "Score", y = "neu",  ax = axs[1])
sns.barplot(data=vaders, x = "Score", y = "neg",  ax = axs[2])


axs[0].set_title("Positive")
axs[1].set_title("Neutral")
axs[2].set_title("Negative")

plt.show()





!pip install transformers

from transformers import pipeline

pipe = pipeline("sentiment-analysis")

from transformers import pipeline

# Step 3: Load the sentiment-analysis pipeline
sentiment_analyzer = pipeline("sentiment-analysis")

# Step 4: Provide input texts
texts = [
    "I love learning with Hugging Face!",
    "This movie was terrible and a waste of time.",
    "I'm feeling okay, not too great, not too bad.",
    "The product quality exceeded my expectations."
]

# Step 5: Run sentiment analysis
results = sentiment_analyzer(texts)

# Step 6: Display the results
for text, result in zip(texts, results):
    print(f"Text: {text}")
    print(f"Sentiment: {result['label']}, Score: {result['score']:.4f}")
    print("-" * 50)

